### ISSUE TITLE
Windows make build patch

### ISSUE THREAD

**Issue by TACIXAT** [angr/vex#39]
Patch for Windows build using `make` installed from [choco](https://stackoverflow.com/a/54086635/1176872). Might just be `make` version opinions. Feel free to close, just wanted to document for others. 

```diff
1c1
< !include common.mk
---
> include common.mk
7c7
< !if "$(MULTIARCH)" == "1"
---
> ifeq "$(MULTIARCH)" "1"
9c9
< !else
---
> else
11c11
< !endif
---
> endif
34c34
< pub\libvex_guest_offsets.h: $(PUB_HEADERS) auxprogs/genoffsets.c
---
> pub/libvex_guest_offsets.h: $(PUB_HEADERS) auxprogs/genoffsets.c
```

**Comment by rhelmot** [comment]
is this for makefile-gcc or makefile-msvc?

**Comment by TACIXAT** [comment]
Makefile-msvc.

**Comment by ltfish** [comment]
These are the changes you will need to do if you are using GNU Make instead of NMake on Windows. We do not officially support running GNU Make on Windows to build pyvex.
