### ISSUE TITLE
Mismatch on comments

### ISSUE THREAD

**Issue by mustakcsecuet** [angr/vex#5]
There is mismatch in two different instruction description on file: vex/pub/libvex_ir.h

Line 111:
 PUT(0) = t1                 # put %eax

Line 155:
STle(t3) = t0

First one has incorrect assignment direction from my understanding, that should be
PUT(12) = t1

**Comment by zardus** [comment]
This repository is just a fork of Valgrind's VEX with some patches by us to make it usable for static analysis. We didn't write VEX, the amazing folk at the Valgrind project (http://valgrind.org) did. Could you submit the bug report to them (http://valgrind.org/support/bug_reports.html)?

**Comment by mustakcsecuet** [comment]
Okay.
